### ISSUE TITLE
Prb launching new notebook

### ISSUE THREAD

**Issue by grobbie** [canonical/notebook-operators#17]
Hi folks
I got a spinner of death waiting while launching a jupyter notebook several times. Seems to be because by default the notebook storage volume dropdown on the launch page is set to "existing" - however no volume exists.

Changing the value to "new" in the dropdown, the problem goes away.

It would be good to make the default notebook storage volume dropdown item "new" and also to do a validation check if there's an existing volume, provide user with an error message if they try to launch a notebook server with an existing volume when there isn't one.

**Comment by DomFleischmann** [comment]
I haven't been able to reproduce this successfully as it defaults to new in my fresh installation. The Notebook Server creation form does switch to "existing" when a volume with the name already exists. So there might have been some preexisting volume that screwed with that.
