### ISSUE TITLE
Update build and scan action with integration testing of updated images

### ISSUE THREAD

**Issue by i-chvets** [canonical/notebook-operators#195]
# Update build and scan action with integration testing of updated images
- Convert build and scan action to use tox.
- Remove `notebooks-controller` and `jupyter-web-app` from list of images that are deleted after scan.
- Add integration testing that uses newly built image for `notebooks-controller` and `jupyter-web-app`
- Add tox integration testing step in build and scan action to run bundle integration test on built containers images for `notebooks-controller` and `jupyter-web-app`

## Testing

**Comment by kimwnasptd** [comment]
Closing for now, since we have a process for building/scanning ROCKs in each rock repo
