### ISSUE TITLE
Add Istio relation to Jupyter Controller

### ISSUE THREAD

**Issue by i-chvets** [canonical/notebook-operators#234]
# Description

After Istio event handling is improved Jupyter Controller should be modified to use Istio relation to obtain gateway info.

**Comment by kimwnasptd** [comment]
This is indeed an issue with this Charm, and most probably with other Charms as well.

We'll need to have a more concentrated effort to evaluate how many charms we will need to modify, to ensure all CKF Charms are reading this information dynamically.

I'll close this issue and will follow up with a product ticket to evaluate the story around having a GW with a different name
