### ISSUE TITLE
Add notebooks integration test

### ISSUE THREAD

**Issue by i-chvets** [canonical/notebook-operators#235]
# Description
Integration tests should be expanded to test creation and operation of notebooks.
Notebooks should be created and sample examples should be executed.

**Comment by ca-scribner** [comment]
I think testing execution of sample examples might be unnecessary (the notebook controller is responsible for creating notebooks.  What image the user fires up inside that notebook is out of scope for testing).  But otherwise agreed

**Comment by i-chvets** [comment]
The use case is for testing with the notebook images that we have built. Not so much testing controller, but notebook images themselves. For example, library update happened to one of the notebooks, we re-build it or take that notebook from upstream, run the test using one of our examples and observe it's failure due to new library that we did not expect.

**Comment by kimwnasptd** [comment]
Closing this as we have the sanity tests to ensure the notebook ROCKs can be started. Then the tests here will verify that the Notebook can become ready
