### ISSUE TITLE
Upgrade handling in Jupyter Controller

### ISSUE THREAD

**Issue by i-chvets** [canonical/notebook-operators#238]
# Description
Jupyter Controller sidecar implementation does not handle upgrade from PodSpec charm due to `deployment` definition in `metadata.yaml':
```
- deployment:
  -  type: stateless
  -  service: omit
```
Upgrade fails with Juju reporting charm incompatibility: 
`juju.errors.JujuAPIError: Juju on containers does not support updating deployment info for services.`

Refer to #232 for more details.

**Comment by kimwnasptd** [comment]
Closing this as we handled it during the CKF 1.8 upgrade
https://github.com/canonical/bundle-kubeflow/issues/732
