### ISSUE TITLE
Notebook volumes mounted read-only on MicroK8s

### ISSUE THREAD

**Issue by grobbie** [canonical/notebook-operators#25]
For some reason every time I launch a new notebook server the volumes (root and data) are mounted read-only. I always check "read-write once" but it doesn't make a difference. The only way to successfully launch a notebook server is to run with ephemeral storage.

**Environment**
Microk8s 1.21/stable
2 node cluster
Microk8s storage add-on enabled
Charmed Kubeflow 1.4

**Comment by ca-scribner** [comment]
hmm to start with I'm not sure what is going on.  I've got 1.4 on microk8s right now and the PVCs on my notebooks are not read only.  Not sure what could be different to give us different results

**Comment by DomFleischmann** [comment]
I also just tried this and haven't been able to reproduce it, the only difference I see with out setups is the clustered microk8s.

**Comment by grobbie** [comment]
these steps solve the issue, I will update the install guide.

```bash
microk8s enable openebs

# on each machine in the cluster {
sudo systemctl enable iscsid
sudo systemctl start iscsid
# }

# change default storageclass to OpenEBS Jiva
microk8s.kubectl patch storageclass microk8s-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
microk8s.kubectl patch storageclass openebs-jiva-default -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class":"true"}}}'

# if you have fewer than 3 nodes in your MicroK8s cluster, do this {
cat > patch.yaml <<EOF
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "1"
EOF
microk8s.kubectl patch storageclass openebs-jiva-default --patch-file patch.yaml
# }
```
