### ISSUE TITLE
Missing notebook image mindspore

### ISSUE THREAD

**Issue by i-chvets** [canonical/notebook-operators#255]
# Description
Mindspore notebook image is not available. It is one of the default images and it is displayed in Jupyter Web App UI.

When trying to pull image using URL specified in UI:
```
docker pull swr.cn-south-1.myhuaweicloud.com/mindspore/jupyter-mindspore:v1.6.1
Error response from daemon: manifest for swr.cn-south-1.myhuaweicloud.com/mindspore/jupyter-mindspore:v1.6.1 not found: manifest unknown: Not Found tag
```

**Comment by SamirPS** [comment]
If i list the tag,i have this

```bash
sudo docker run --rm quay.io/skopeo/stable list-tags docker://swr.cn-south-1.myhuaweicloud.com/mindspore/jupyter-mindspore
{
    "Repository": "swr.cn-south-1.myhuaweicloud.com/mindspore/jupyter-mindspore",
    "Tags": [
        "v1.6.0-rc.1"
    ]
}
```

I have only the v1.6.0-rc.1 tag

**Comment by NohaIhab** [comment]
Based on discussions, We'll remove the mindspore image from the notebook images until further notice. Communication is needed with owners of the image.

**Comment by DnPlas** [comment]
This image was removed by https://github.com/canonical/notebook-operators/pull/293, no need for it in further releases.
