### ISSUE TITLE
Notebook content is removed on every start stop

### ISSUE THREAD

**Issue by Barteus** [canonical/notebook-operators#312]
### Bug Description

When I create a notebook using the default notebook image - charmedkubeflow/jupyter-scipy:v1.7.0_20.04_1

New notebooks are created in the /var/lib/pebble/default instead of the volume that is attached to the Pod under /home/jovyan/

### To Reproduce

1. Deploy Kubeflow
2. Create a notebook
3. Open the notebook and create a new ipynb
4. Stop the notebook and start it again
5. File is missing

Expected: Files exists after notebook restart.

### Environment

- GCP VM
- microk8s 1.24/stable
- Kubeflow 1.7

### Relevant log output

```shell
**Notebook**
$ !pwd
/var/lib/pebble/default
```

**Comment by kimwnasptd** [comment]
This is now fixed in the `1.7/stable` bundle. The fix was introduced in
https://github.com/canonical/kubeflow-rocks/pull/61
https://github.com/canonical/notebook-operators/pull/314

We'll need to keep this in mind though when creating our ROCKs for 1.8
