### ISSUE TITLE
Create a spec for NGC container Notebook integration

### ISSUE THREAD

**Issue by NohaIhab** [canonical/notebook-operators#326]
### What needs to get done

A spec that outlines the context, implementation details and the user experience of how we will enable running a Notebook in Charmed Kubeflow using and NGC contaienr. 
The implementation section must include:
* The definition of the PodDefault that configures JupyterLab
* Explain how the PodDefault gets applied (via config? via relation to resource dispatcher? charm action?) 
* what namespace the PodDefault is applied in?

### Why it needs to get done

To define and discuss the epic of NGC container Notebook integration.

**Comment by DnPlas** [comment]
This task has been already completed. The spec has been reviewed and approved by @ca-scribner, @kimwnasptd and @DnPlas.
