### ISSUE TITLE
Re-enable test_notebook tests

### ISSUE THREAD

**Issue by agathanatasha** [canonical/notebook-operators#34]
The bundle integration `test_notebook` test is disabled due to https://github.com/kubeflow/kubeflow/issues/6056. When that issue is resolved, we should re-enable the test.

**Comment by i-chvets** [comment]
When enabled this test never finishes.
```
  integration: FAIL code -15 (7580.92=setup[0.03]+cmd[7580.88] seconds)
  evaluation failed :( (7580.97 seconds)
```
