### ISSUE TITLE
No "Allow access to Minio/MLFlow" option in dropdown menu

### ISSUE THREAD

**Issue by DnPlas** [canonical/notebook-operators#55]
#### Observed behaviour

We are missing the "Allow access to Minio/MLFlow" options in the "Configurations" drop down menu when creating a Notebook.

#### Environment

* Microk8s 1.22
* Kubeflow 1.6/beta (no overlays)
* Metallb enabled

#### Steps to reproduce

1. `juju deploy kubeflow --channel 1.6/beta --trust`
2. Configure dex and oidc to get [access to the dashboard](https://charmed-kubeflow.io/docs/dashboard)
3. Access the dashboard > Notebooks > New notebook
4. Go to "Configurations" section and click on the drop down menu
<img width="691" alt="Screenshot 2022-08-29 at 21 42 30" src="https://user-images.githubusercontent.com/18201737/187336820-3a876a9b-0c1f-4f54-93c7-db414fac2892.png">

#### Expected behaviour

Have "Allow access to Minio/MLFlow" options in the drop down menu

**Comment by ca-scribner** [comment]
I think to solve this we need to add a `PodDefault` like [this](https://github.com/canonical/ai-ml-demos/blob/8838e896c53c7269a84cf517636c3eed7f6a3b14/kubecon-eu-2022/datacenter/minio-jupyter-config.yaml) to every user's namespace.  

What I am confused about is that this is reported as a regression.  Not saying it isn't, just saying that I didn't think we had an elegant way of implementing this solution so I'm not sure how it could have worked before.  Does anyone know where it was implemented?  For the "Allow access to Kubeflow Pipelines", we had to use a hacky fix that [modifies the metacontroller KFP already uses](https://github.com/canonical/kfp-operators/blob/b534b87bd0a0f547e22541d424329a83d77e38b7/charms/kfp-profile-controller/files/upstream/sync.py#L386)

Are we sure this wasn't something that people were adding manually?  I see in some of the demos ([1](https://github.com/canonical/ai-ml-demos/blob/8838e896c53c7269a84cf517636c3eed7f6a3b14/kubecon-eu-2022/datacenter/minio-jupyter-config.yaml), [2](https://github.com/canonical/kubeflow-examples/blob/12103ce05f15fc3ae97841bf22653d26f6bae7ce/e2e-wine-kfp-mlflow/permissions/allow-mlflow.yaml)) these being implemented, which says to me they were manually added to user namespaces.

[^1]: https://github.com/canonical/ai-ml-demos/blob/8838e896c53c7269a84cf517636c3eed7f6a3b14/kubecon-eu-2022/datacenter/minio-jupyter-config.yaml

**Comment by i-chvets** [comment]
[Jira](https://warthogs.atlassian.net/browse/KF-625)

**Comment by kimwnasptd** [comment]
This is solved by relating the `resource-dispatcher` with MLFlow
