### ISSUE TITLE
Notebook spawner page has non-descriptive groups for available server `Image`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/notebook-operators#65]
### What did you observe 

On the notebook spawner page (Dashboard->Notebooks->New Notebook), the `Image` section offers different groups of image, like shown here:

![Screenshot from 2022-11-18 09-39-08](https://user-images.githubusercontent.com/48125859/202730665-c7ee98f8-5784-4eff-a5bc-e7901571feb3.png)

The Jupyterlab image group is descriptive, but what "1" and "2" means is not (for example, it is not clear that "2" offers rstudio).  

### What did you expect

The headings "1" and "2" should be more descriptive, saying what each group means

### Additional Details

This might be a misconfiguration in our [spawner config](https://github.com/canonical/notebook-operators/blob/c124e1b0a5b84b0868ced6fd96736cae5e122c8b/charms/jupyter-ui/src/spawner_ui_config.yaml#L29), or could be something upstream.

**Comment by DnPlas** [comment]
Thanks @ca-scribner, let's confirm this is an issue in the upstream implementation before we work on it.

**Comment by misohu** [comment]
There is configfile called `logos-configmap.yaml` in charm which has svgs for those images. I updated those to python and r logo in this PR: logos-configmap.yaml
