### ISSUE TITLE
Issue deploying the bundle

### ISSUE THREAD

**Issue by aym-frikha** [canonical/notebook-operators#9]
Hello ,

When trying to deploy this bundle, I had this issue in the jupyter-controller pod:
controller-runtime.source       if kind is a CRD, it should be installed before calling Start   {"kind": "VirtualService.networking.istio.io", "error": "no matches for kind \"VirtualService\" in version \"networking.istio.io/v1alpha3\""}

Seems it's expecting istio to be deployed.

**Comment by knkski** [comment]
@aym-frikha: Yeah, that's unfortunately required, as `jupyter-controller` generates a VirtualService for connecting to each notebook server. See here for where we do that as part of CI:

https://github.com/canonical/bundle-jupyter/blob/master/.github/workflows/integrate.yaml#L53-L57

I think this should definitely be documented somewhere, though
